version: "3.9"

services:
  db:
    container_name: db
    image: postgres:alpine
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDB_VENDOR=postgres
      - PGDATA=/var/lib/postgresql/data
    restart: always

  web:
    build:
      context: .
    container_name: backend
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./src:/usr/src/app
    ports:
      - 5055:8000
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - SHOW_DEBUGGER_TOOLBAR=${SHOW_DEBUGGER_TOOLBAR}
    restart: always

